# Generated by Django 2.2.5 on 2019-09-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('released', models.DateTimeField(blank=True, null=True)),
                ('na_sales', models.DecimalField(decimal_places=4, max_digits=5)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdata.Genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdata.Platform')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdata.Publisher')),
            ],
        ),
    ]
